# Generated by Django 5.2.6 on 2025-01-17 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='First number')),
                ('y', models.IntegerField(help_text='Second number')),
                ('result', models.IntegerField(help_text='Calculation result')),
                ('server_id', models.IntegerField(help_text='ID of the server that processed this calculation')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the task was created')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When the task was completed')),
            ],
            options={
                'verbose_name': 'Calculation',
                'verbose_name_plural': 'Calculations',
                'ordering': ['-processed_at'],
            },
        ),
    ]